export type SeoLandingPage = {
  slug: string;
  title: string;
  primaryKeyword: string;
  keywords: readonly string[];
  description: string;
  eyebrow: string;
  intro: readonly string[];
  features: readonly { title: string; body: string }[];
  benefits: readonly string[];
  integration: string;
  industries: readonly string[];
  faqs: readonly { question: string; answer: string }[];
  related: readonly { label: string; href: string }[];
  image: string;
  schemaType: 'Product' | 'SoftwareApplication' | 'Service';
};

export const seoLandingPages: readonly SeoLandingPage[] = [
  {
    slug: 'biometric-attendance-system',
    title: 'Biometric Attendance System for Modern Workplaces',
    primaryKeyword: 'biometric attendance system',
    keywords: ['biometric attendance system', 'employee attendance system', 'fingerprint attendance', 'face attendance system', 'attendance system India'],
    description: 'Plan biometric attendance with face or fingerprint authentication, centralized reporting, shift workflows, and HRMS integration for Indian workplaces.',
    eyebrow: 'Attendance solutions',
    intro: [
      'A biometric attendance system records workforce time events through an approved biological identifier such as a face or fingerprint. It can replace manual registers and disconnected spreadsheets with a more consistent input for attendance review.',
      'Indian Infotech brings devices, Easytime Online, HRMS, payroll context, and implementation support into one scoped solution. The right design depends on workforce size, shift patterns, locations, operating environment, and integration requirements.',
    ],
    features: [
      { title: 'Face and fingerprint options', body: 'Choose an authentication method around hygiene, throughput, workforce profile, and site conditions.' },
      { title: 'Real-time attendance flow', body: 'Connect supported devices to a central workflow for timely review of punches and exceptions.' },
      { title: 'Multi-location oversight', body: 'Plan consistent attendance capture and reporting across offices, branches, factories, or project sites.' },
      { title: 'HRMS and payroll readiness', body: 'Confirm how approved attendance records should move into leave, shift, HRMS, and payroll processes.' },
    ],
    benefits: ['Reduce manual attendance entry and avoidable transcription errors', 'Make missing punches and shift exceptions easier to review', 'Improve workforce visibility across approved locations', 'Prepare cleaner attendance inputs for downstream payroll review'],
    integration: 'Biometric terminal → Easytime Online → attendance review → approved HRMS or payroll workflow.',
    industries: ['Manufacturing', 'Pharmaceutical', 'Chemical', 'Textile', 'Corporate offices', 'Education', 'Healthcare', 'Logistics'],
    faqs: [
      { question: 'What is a biometric attendance system?', answer: 'It records attendance using a biological characteristic such as a fingerprint or face, then makes those events available to an attendance workflow.' },
      { question: 'Can it work across multiple locations?', answer: 'Yes, a multi-location design can centralize supported device data while preserving the review responsibilities of each site.' },
      { question: 'Can biometric attendance integrate with HRMS and payroll?', answer: 'Supported attendance data can feed HRMS and payroll processes after compatibility, policy rules, and approval ownership are confirmed.' },
      { question: 'Which is better: face or fingerprint attendance?', answer: 'The better method depends on environment, hygiene, throughput, workforce needs, and security policy. Indian Infotech can help compare both options.' },
      { question: 'What is needed before deployment?', answer: 'A useful assessment covers workforce size, shifts, locations, network conditions, entry flow, reporting, and existing software.' },
    ],
    related: [{ label: 'Face recognition attendance systems', href: '/face-recognition-attendance-system' }, { label: 'Fingerprint attendance machines', href: '/fingerprint-attendance-machine' }, { label: 'Attendance management software', href: '/attendance-management-software' }],
    image: '/campaign/core-systems/easytime-desktop-v2.webp', schemaType: 'Service',
  },
  {
    slug: 'face-recognition-attendance-system',
    title: 'Face Recognition Attendance System for Contactless Time Tracking',
    primaryKeyword: 'face recognition attendance system',
    keywords: ['face recognition attendance system', 'facial recognition attendance', 'contactless attendance system', 'face attendance machine', 'workforce attendance India'],
    description: 'Explore contactless face recognition attendance systems with workplace devices, attendance software, reporting, and deployment guidance from Indian Infotech.',
    eyebrow: 'Face attendance',
    intro: [
      'A face recognition attendance system identifies an enrolled user without requiring a fingerprint touch. It can support quick authentication at offices, plants, institutions, and other busy workforce entry points.',
      'Indian Infotech offers facial-recognition devices within a broader attendance and access portfolio. Device placement, lighting, user flow, data synchronization, fallback rules, and software compatibility are confirmed before rollout.',
    ],
    features: [
      { title: 'Contactless authentication', body: 'Support attendance capture without requiring users to touch a shared fingerprint sensor.' },
      { title: 'Visible-light device options', body: 'Review suitable facial-recognition terminals from the published Indian Infotech attendance portfolio.' },
      { title: 'Attendance and access context', body: 'Plan whether the endpoint records attendance, supports an approved access workflow, or serves both roles.' },
      { title: 'Central reporting', body: 'Route supported events into Easytime Online or another confirmed workforce process for review.' },
    ],
    benefits: ['Improve throughput at busy attendance points', 'Support contactless workforce authentication', 'Reduce dependence on cards or manual registers', 'Connect attendance events to a centralized review process'],
    integration: 'Face terminal → network synchronization → Easytime Online → shift and exception review.',
    industries: ['Corporate offices', 'Manufacturing', 'Education', 'Healthcare', 'Hospitality', 'Logistics'],
    faqs: [
      { question: 'How does face recognition attendance work?', answer: 'An enrolled facial template is used to identify a user at a compatible terminal, which records an attendance event for synchronization and review.' },
      { question: 'Is face attendance completely contactless?', answer: 'Facial authentication itself is contactless. The complete journey still depends on device placement, entry flow, and any connected door or barrier.' },
      { question: 'Does it work in every lighting condition?', answer: 'Performance depends on the selected device and environment, so lighting and installation position should be checked during a site assessment.' },
      { question: 'Can face attendance support multiple offices?', answer: 'A supported cloud or centralized attendance setup can consolidate events from multiple configured locations.' },
      { question: 'Which Indian Infotech products support facial recognition?', answer: 'The published portfolio includes AI 60, Mini AI-10, and Mini AI-30. Exact capability and compatibility should be confirmed for the selected configuration.' },
    ],
    related: [{ label: 'View facial-recognition devices', href: '/products#attendance' }, { label: 'Biometric attendance systems', href: '/biometric-attendance-system' }, { label: 'Cloud attendance systems', href: '/cloud-attendance-system' }],
    image: '/posters/ai-60.webp', schemaType: 'Service',
  },
  {
    slug: 'fingerprint-attendance-machine',
    title: 'Fingerprint Attendance Machine for Reliable Workforce Records',
    primaryKeyword: 'fingerprint attendance machine',
    keywords: ['fingerprint attendance machine', 'biometric attendance device', 'fingerprint time clock', 'employee attendance machine', 'attendance hardware India'],
    description: 'Compare fingerprint attendance machines for workforce time tracking, access workflows, software synchronization, and multi-site reporting.',
    eyebrow: 'Fingerprint attendance',
    intro: [
      'A fingerprint attendance machine gives employees a direct biometric method for recording arrival, departure, and approved attendance events. It remains a practical choice for many workplaces where enrollment and sensor use fit the operating environment.',
      'Indian Infotech helps match fingerprint devices to the required throughput, location, access role, connectivity, and attendance software. Configuration is selected around the real workflow rather than a model name alone.',
    ],
    features: [
      { title: 'Fingerprint authentication', body: 'Use enrolled fingerprint templates for attendance or controlled personnel-entry workflows.' },
      { title: 'Attendance device selection', body: 'Compare published devices by application, environment, and the workforce journey at each point.' },
      { title: 'Exception planning', body: 'Define fallback handling for enrollment, unread fingerprints, missed events, and offline operation.' },
      { title: 'Software compatibility review', body: 'Confirm synchronization, reporting, HRMS, and payroll requirements before purchase.' },
    ],
    benefits: ['Replace paper-based attendance capture', 'Create a consistent employee authentication process', 'Support reviewable attendance event records', 'Combine attendance and access needs where the configuration permits'],
    integration: 'Fingerprint machine → attendance synchronization → exception review → approved workforce records.',
    industries: ['Manufacturing', 'Textile', 'Engineering', 'Corporate offices', 'Education', 'Warehousing'],
    faqs: [
      { question: 'What does a fingerprint attendance machine record?', answer: 'It records an attendance event when an enrolled user is successfully authenticated, subject to the device and configured attendance workflow.' },
      { question: 'Can a fingerprint device also control a door?', answer: 'Some products support access-control use. The reader, controller, lock, power, safety, and software design must be confirmed together.' },
      { question: 'How are failed fingerprint reads handled?', answer: 'Enrollment quality, sensor care, fallback methods, and an approved exception process should be defined during implementation.' },
      { question: 'Can fingerprint attendance connect to payroll?', answer: 'Approved attendance records can support payroll inputs when software compatibility and policy rules are correctly configured.' },
      { question: 'Which fingerprint products are available?', answer: 'Indian Infotech publishes I-18, I-202, and IS-500 within its biometric access and attendance portfolio.' },
    ],
    related: [{ label: 'Browse fingerprint and access devices', href: '/products#access-control' }, { label: 'Time attendance software', href: '/time-attendance-software' }, { label: 'Door access control systems', href: '/door-access-control-system' }],
    image: '/posters/is-500.webp', schemaType: 'Service',
  },
  {
    slug: 'attendance-management-software',
    title: 'Attendance Management Software for Shifts, Leave and Reporting',
    primaryKeyword: 'attendance management software',
    keywords: ['attendance management software', 'employee time tracking software', 'shift attendance software', 'workforce attendance reporting', 'attendance software India'],
    description: 'Centralize employee attendance, shifts, leave, exceptions, reporting, and approved payroll inputs with Indian Infotech workforce software.',
    eyebrow: 'Attendance software',
    intro: [
      'Attendance management software turns raw device punches into records that managers and HR teams can review. It provides the working layer for shifts, leave, overtime context, missed events, reports, and approved downstream use.',
      'Indian Infotech positions Easytime Online within a connected attendance ecosystem. The deployment can be scoped for one organization or a distributed workforce, with rules, roles, devices, reporting, and integrations confirmed during design.',
    ],
    features: [
      { title: 'Shift and attendance review', body: 'Bring punches, shifts, leave context, and exceptions into a defined operational review.' },
      { title: 'Multi-company and multi-location scope', body: 'Plan centralized oversight for approved companies, branches, factories, or offices.' },
      { title: 'Attendance reporting', body: 'Give responsible teams clearer records for daily review and management reporting.' },
      { title: 'Integration planning', body: 'Confirm the approved data flow to HRMS, payroll, ERP, or other business systems.' },
    ],
    benefits: ['Reduce spreadsheet consolidation', 'Speed up attendance exception review', 'Create clearer ownership for corrections and approvals', 'Prepare consistent records for HR and payroll teams'],
    integration: 'Attendance devices → Easytime Online → HR review → approved HRMS, payroll, ERP, or reporting output.',
    industries: ['Manufacturing', 'Pharmaceutical', 'Corporate offices', 'Construction', 'Retail', 'Logistics'],
    faqs: [
      { question: 'What is attendance management software?', answer: 'It organizes attendance events with shifts, leave, exceptions, approvals, and reports so responsible teams can review workforce time records.' },
      { question: 'Does the software require biometric devices?', answer: 'A deployment may use supported biometric or other attendance endpoints. The input method and compatibility should be confirmed for the site.' },
      { question: 'Can it manage multiple locations?', answer: 'Easytime Online is positioned for centralized multi-location use, subject to connectivity, device, and account configuration.' },
      { question: 'Can attendance records be exported to payroll?', answer: 'Supported approved records can flow to payroll or other systems after fields, rules, responsibilities, and integration method are validated.' },
      { question: 'Can managers correct missed punches?', answer: 'Exception workflows depend on configured roles and policies. The approval process should be agreed during implementation.' },
    ],
    related: [{ label: 'Explore Easytime Online', href: '/software/easytime-online' }, { label: 'HRMS software', href: '/hrms-software' }, { label: 'Payroll software', href: '/payroll-software' }],
    image: '/campaign/core-systems/easytime-desktop-v2.webp', schemaType: 'SoftwareApplication',
  },
  {
    slug: 'cloud-attendance-system',
    title: 'Cloud Attendance System for Multi-Location Workforces',
    primaryKeyword: 'cloud attendance system',
    keywords: ['cloud attendance system', 'cloud-based attendance software', 'multi-location attendance', 'online attendance management', 'remote workforce attendance'],
    description: 'Centralize attendance from multiple offices, branches, plants, or sites with cloud reporting, controlled access, and implementation support.',
    eyebrow: 'Cloud attendance',
    intro: [
      'A cloud attendance system helps distributed organizations review workforce time records without maintaining a separate attendance process at every location. Supported devices send events into a centralized environment where authorized users can review shifts, leave, and exceptions.',
      'Indian Infotech uses Easytime Online as the workforce layer for this model. Network reliability, device compatibility, user roles, data flow, rollout sequence, and support ownership are validated before a multi-site deployment.',
    ],
    features: [
      { title: 'Centralized location view', body: 'Bring configured attendance records from multiple sites into one approved review environment.' },
      { title: 'Role-based operations', body: 'Define which administrators and local managers can review or act on workforce records.' },
      { title: 'Phased rollout support', body: 'Sequence devices, locations, training, and cutover in practical stages.' },
      { title: 'Cloud reporting workflow', body: 'Make attendance information available to authorized teams without manual site-by-site consolidation.' },
    ],
    benefits: ['Reduce fragmented location reporting', 'Support consistent attendance processes across sites', 'Give central teams more timely visibility', 'Scale rollout in controlled phases'],
    integration: 'Remote site devices → secure network flow → Easytime Online → authorized reporting and downstream review.',
    industries: ['Retail', 'Logistics', 'Construction', 'Corporate groups', 'Education networks', 'Multi-plant manufacturing'],
    faqs: [
      { question: 'What is a cloud attendance system?', answer: 'It centralizes supported attendance data in an online platform so authorized users can review workforce records across configured locations.' },
      { question: 'Does cloud attendance work when a site loses internet?', answer: 'Offline behavior depends on the selected device and configuration. Storage, synchronization, and exception handling must be confirmed before deployment.' },
      { question: 'Can different branches have separate managers?', answer: 'Roles can be planned around central and local responsibilities, subject to the capabilities and configuration of the selected software.' },
      { question: 'Is cloud attendance suitable for factories?', answer: 'It can suit factories when shift complexity, network conditions, device placement, and review ownership are carefully assessed.' },
      { question: 'How is a multi-location rollout planned?', answer: 'Start with location and network discovery, validate a pilot, train owners, then sequence additional sites with defined support.' },
    ],
    related: [{ label: 'Easytime Online cloud attendance', href: '/software/easytime-online' }, { label: 'Multi-location attendance planning', href: '/solutions/multi-location-attendance' }, { label: 'Workforce management software', href: '/workforce-management-software' }],
    image: '/campaign/hero/workforce-desktop-v2.webp', schemaType: 'SoftwareApplication',
  },
  {
    slug: 'hrms-software',
    title: 'HRMS Software in India for Connected Employee Operations',
    primaryKeyword: 'HRMS software India',
    keywords: ['HRMS software India', 'human resource management software', 'employee lifecycle software', 'HR and attendance system', 'workforce management platform'],
    description: 'Connect employee records, attendance, leave, payroll, self-service, recruitment, performance, and lifecycle workflows with Indian Infotech HRMS software.',
    eyebrow: 'Human resources software',
    intro: [
      'HRMS software gives HR teams a structured place to manage employee information and the processes that depend on it. A useful implementation connects records, roles, attendance, leave, payroll inputs, documents, self-service, and lifecycle responsibilities.',
      'Indian Infotech offers an HRMS and payroll portfolio for organizations in India. Modules are selected around the current process, policy ownership, users, approvals, integrations, security, reporting, and rollout priorities.',
    ],
    features: [
      { title: 'Core HR records', body: 'Organize approved employee information with clear ownership and access responsibilities.' },
      { title: 'Attendance and leave context', body: 'Connect workforce time records and leave processes to the wider employee lifecycle.' },
      { title: 'Employee self-service', body: 'Give employees an approved route to manage relevant information and requests.' },
      { title: 'Lifecycle modules', body: 'Plan recruitment, onboarding, performance, training, documents, assets, and exit workflows as needed.' },
    ],
    benefits: ['Reduce disconnected employee records', 'Make approvals and ownership easier to understand', 'Connect attendance context with HR operations', 'Support consistent employee lifecycle processes'],
    integration: 'Employee records + attendance + leave → HRMS review → approved payroll and employee workflows.',
    industries: ['Manufacturing', 'Pharmaceutical', 'Corporate offices', 'Engineering', 'Education', 'Healthcare', 'Logistics'],
    faqs: [
      { question: 'What is HRMS software?', answer: 'HRMS software supports employee records and related processes such as attendance, leave, payroll inputs, documents, self-service, performance, and lifecycle workflows.' },
      { question: 'Which HRMS modules does Indian Infotech publish?', answer: 'The portfolio includes core HR and payroll, claims, documents, assets, attendance, self-service, performance, training, onboarding, exit, and recruitment modules.' },
      { question: 'Can HRMS integrate with biometric attendance?', answer: 'Supported attendance data can be connected after device, field, policy, exception, and integration requirements are confirmed.' },
      { question: 'Is HRMS suitable for a growing company?', answer: 'Yes, when modules and rollout stages are selected around the company’s current maturity instead of activating unnecessary complexity.' },
      { question: 'How should an HRMS implementation begin?', answer: 'Document employee data, roles, policies, approvals, current systems, reporting needs, and the first high-value workflow to implement.' },
    ],
    related: [{ label: 'Explore HRMS and payroll', href: '/software/hrms-payroll' }, { label: 'Browse HRMS modules', href: '/hrms-payroll' }, { label: 'Attendance management software', href: '/attendance-management-software' }],
    image: '/campaign/core-systems/hrms-payroll-desktop-v2.webp', schemaType: 'SoftwareApplication',
  },
  {
    slug: 'payroll-software',
    title: 'Payroll Software in India Connected to Attendance and HRMS',
    primaryKeyword: 'payroll software India',
    keywords: ['payroll software India', 'payroll and attendance software', 'HRMS payroll system', 'employee payroll workflow', 'payroll management software'],
    description: 'Plan payroll software around approved employee records, attendance inputs, review controls, reporting, and Indian Infotech HRMS workflows.',
    eyebrow: 'Payroll operations',
    intro: [
      'Payroll software depends on accurate employee data, approved time inputs, policy rules, and a disciplined review process. Connecting those responsibilities helps reduce rework before payroll is finalized.',
      'Indian Infotech positions payroll within its broader HRMS portfolio rather than as an isolated calculation screen. The implementation scope is confirmed around employee records, attendance, leave, claims, approvals, outputs, roles, and existing systems.',
    ],
    features: [
      { title: 'Approved payroll inputs', body: 'Define how employee, attendance, leave, and other approved records reach payroll review.' },
      { title: 'Maker-checker workflow', body: 'Plan responsibility for preparation, validation, approval, correction, and final output.' },
      { title: 'HRMS connection', body: 'Keep payroll aligned with the employee records and lifecycle processes that support it.' },
      { title: 'Reporting and handoff', body: 'Confirm the required reports, exports, statutory context, and downstream responsibilities.' },
    ],
    benefits: ['Reduce avoidable manual payroll inputs', 'Make data ownership and approvals clearer', 'Connect attendance exceptions before payroll close', 'Create a more traceable payroll preparation process'],
    integration: 'Approved HRMS records + attendance + leave → payroll preparation → review and authorized output.',
    industries: ['Manufacturing', 'Corporate offices', 'Pharmaceutical', 'Textile', 'Engineering', 'Services'],
    faqs: [
      { question: 'How does attendance connect to payroll software?', answer: 'Approved attendance, shift, leave, and exception records can provide payroll inputs when policies and integration fields are configured correctly.' },
      { question: 'Is payroll included in Indian Infotech HRMS?', answer: 'Payroll is part of the published HRMS and payroll portfolio. Exact modules and deployment scope should be confirmed during a demo.' },
      { question: 'Can payroll be implemented without replacing every HR process?', answer: 'A phased scope can focus on the required records and payroll workflow, provided dependencies and data ownership are understood.' },
      { question: 'What should be prepared before a payroll demo?', answer: 'Bring workforce size, pay cycles, attendance sources, leave rules, current process, approval roles, and required outputs.' },
      { question: 'Does the website promise statutory compliance?', answer: 'No. Current statutory, tax, policy, and product capabilities must be validated for the actual deployment and operating period.' },
    ],
    related: [{ label: 'HRMS and payroll platform', href: '/software/hrms-payroll' }, { label: 'Core HR and payroll module', href: '/hrms-payroll/core-hr-payroll' }, { label: 'Time attendance software', href: '/time-attendance-software' }],
    image: '/campaign/core-systems/hrms-payroll-desktop-v2.webp', schemaType: 'SoftwareApplication',
  },
  {
    slug: 'workforce-management-software',
    title: 'Workforce Management Software for Connected Daily Operations',
    primaryKeyword: 'workforce management software',
    keywords: ['workforce management software', 'employee workforce platform', 'time and attendance management', 'multi-site workforce system', 'workforce operations India'],
    description: 'Connect attendance, shifts, leave, employee records, HRMS, payroll, and multi-location reporting with Indian Infotech workforce software.',
    eyebrow: 'Workforce operations',
    intro: [
      'Workforce management software connects the daily records and decisions behind employee operations. Attendance events become more useful when shifts, leave, exceptions, HR records, payroll inputs, reporting, and responsible owners work together.',
      'Indian Infotech combines Easytime Online with HRMS and payroll workflows to support this connected model. A practical rollout starts with the operating problem, then confirms modules, data, roles, devices, locations, and integrations.',
    ],
    features: [
      { title: 'Attendance and shift visibility', body: 'Review supported workforce events in the context of shifts, leave, exceptions, and locations.' },
      { title: 'Employee workflow connection', body: 'Link relevant attendance records to HRMS, self-service, lifecycle, and payroll responsibilities.' },
      { title: 'Multi-location operations', body: 'Define central oversight and local review ownership for a distributed workforce.' },
      { title: 'Modular rollout', body: 'Start with the highest-value workflow and add confirmed modules as process maturity grows.' },
    ],
    benefits: ['Create one clearer view of workforce operations', 'Reduce handoffs between disconnected records', 'Improve accountability for exceptions and approvals', 'Support consistent processes across growing locations'],
    integration: 'Workforce devices + Easytime Online + HRMS modules → approved operational and payroll workflows.',
    industries: ['Manufacturing', 'Pharmaceutical', 'Corporate offices', 'Retail', 'Construction', 'Logistics', 'Education'],
    faqs: [
      { question: 'What does workforce management software include?', answer: 'The scope can include attendance, shifts, leave, reporting, employee records, self-service, HRMS, payroll inputs, and related approval workflows.' },
      { question: 'Is workforce management the same as HRMS?', answer: 'They overlap, but workforce management often emphasizes daily time and staffing operations while HRMS covers broader employee records and lifecycle processes.' },
      { question: 'Can it support a distributed workforce?', answer: 'Yes, when location roles, connectivity, device synchronization, policies, and central reporting are deliberately configured.' },
      { question: 'Do all modules need to launch together?', answer: 'No. A phased implementation can begin with attendance or core HR and add modules after the first workflow is stable.' },
      { question: 'How does Indian Infotech scope a solution?', answer: 'The team reviews workforce size, locations, shifts, current tools, approvals, reporting, hardware, integrations, and support expectations.' },
    ],
    related: [{ label: 'Attendance management software', href: '/attendance-management-software' }, { label: 'HRMS software in India', href: '/hrms-software' }, { label: 'Explore the workforce platform', href: '/platform#workforce' }],
    image: '/campaign/hero/workforce-desktop-v2.webp', schemaType: 'SoftwareApplication',
  },
  {
    slug: 'access-control-system',
    title: 'Access Control System for Secure Workplace Entry',
    primaryKeyword: 'access control system',
    keywords: ['access control system', 'biometric access control', 'workplace access management', 'door access control', 'commercial access control India'],
    description: 'Plan biometric access control systems with face or fingerprint terminals, doors, barriers, visitor workflows, and site-specific implementation support.',
    eyebrow: 'Workplace security',
    intro: [
      'An access control system manages who can enter a defined area and under what conditions. A complete design can include identity terminals, controllers, doors, locks, barriers, visitor processes, permissions, exception handling, and operating responsibility.',
      'Indian Infotech supplies biometric devices and entrance equipment within a site-led solution process. The system is shaped around people, entry points, controlled zones, safety needs, operating hours, integrations, and support ownership.',
    ],
    features: [
      { title: 'Biometric identity options', body: 'Review face, fingerprint, or connected access methods for the people and environment at each entrance.' },
      { title: 'Access-rule planning', body: 'Define authorized users, schedules, zones, exceptions, visitor handling, and review responsibilities.' },
      { title: 'Door and entrance integration', body: 'Connect compatible terminals with approved doors, locks, flap barriers, turnstiles, or boom barriers.' },
      { title: 'Site assessment', body: 'Confirm power, cabling, network, physical flow, safety, fallback, and support before installation.' },
    ],
    benefits: ['Replace informal entry decisions with a defined process', 'Improve visibility at controlled workplace areas', 'Connect personnel identity with physical entry points', 'Plan exceptions and support before they become operating gaps'],
    integration: 'Authorized identity → access terminal/controller → door or barrier decision → approved event record.',
    industries: ['Pharmaceutical', 'Manufacturing', 'Corporate offices', 'Healthcare', 'Education', 'Banking', 'Logistics'],
    faqs: [
      { question: 'What is an access control system?', answer: 'It combines identity, permissions, physical entry equipment, and operating rules to manage access to a defined workplace area.' },
      { question: 'Can access control use face or fingerprint authentication?', answer: 'Yes, compatible biometric terminals can support facial or fingerprint identity depending on the selected product and site design.' },
      { question: 'Can it connect to turnstiles or flap barriers?', answer: 'A compatible controller and access design can connect identity decisions with entrance equipment after electrical, safety, and workflow requirements are confirmed.' },
      { question: 'Does access control replace visitor management?', answer: 'No. Visitor management handles registration and visit workflow; access control manages physical entry. The two can be planned together.' },
      { question: 'Why is a site assessment important?', answer: 'Each entrance has different people flow, hardware, power, network, emergency, environmental, and support conditions that affect the design.' },
    ],
    related: [{ label: 'Door access control systems', href: '/door-access-control-system' }, { label: 'Visitor management systems', href: '/visitor-management-system' }, { label: 'Browse access-control products', href: '/products#access-control' }],
    image: '/campaign/hero/access-desktop-v2.webp', schemaType: 'Service',
  },
  {
    slug: 'door-access-control-system',
    title: 'Door Access Control System for Offices and Controlled Areas',
    primaryKeyword: 'door access control system',
    keywords: ['door access control system', 'biometric door access', 'door access controller', 'electronic access control', 'workplace door security'],
    description: 'Design biometric door access control with suitable terminals, permissions, locks, interlocks, event records, and deployment guidance.',
    eyebrow: 'Door security',
    intro: [
      'A door access control system links an identity decision to a physical door. The visible reader is only one part of a safe, reliable installation that may also involve a controller, lock, power supply, exit method, sensor, emergency behavior, network, and operating rules.',
      'Indian Infotech helps plan conventional workplace doors and specialized interlock contexts. Exact hardware, authentication, safety, door condition, traffic, permissions, and integration requirements are confirmed at the site.',
    ],
    features: [
      { title: 'Face or fingerprint reader options', body: 'Select a compatible authentication endpoint for the people, throughput, and environment.' },
      { title: 'Permission and schedule design', body: 'Define who can enter, when access applies, how exceptions work, and who reviews records.' },
      { title: 'Door hardware coordination', body: 'Confirm locks, sensors, exit devices, power, cabling, emergency behavior, and existing door suitability.' },
      { title: 'Interlock planning', body: 'Assess multi-door or controlled-room sequences where the operating environment genuinely requires them.' },
    ],
    benefits: ['Control entry to defined rooms and zones', 'Reduce dependence on unmanaged physical keys', 'Create a reviewable access process', 'Coordinate identity, door hardware, and operating safety'],
    integration: 'Biometric or approved credential → access controller → lock/interlock action → access event review.',
    industries: ['Pharmaceutical', 'Research facilities', 'Corporate offices', 'Manufacturing', 'Healthcare', 'Banking'],
    faqs: [
      { question: 'What equipment is needed for biometric door access?', answer: 'A design may require a reader or terminal, controller, compatible lock, power supply, exit device, door sensor, cabling, and approved emergency behavior.' },
      { question: 'Can existing doors be upgraded?', answer: 'Often they can, but door material, frame, lock type, life-safety requirements, traffic, and wiring access must be assessed first.' },
      { question: 'What is a door interlock system?', answer: 'An interlock coordinates two or more doors so their opening sequence follows a defined controlled-area process.' },
      { question: 'Can access permissions follow work schedules?', answer: 'Supported systems can use configured permissions and schedules, subject to the selected controller and software.' },
      { question: 'What happens during a power or network failure?', answer: 'Fail-safe or fail-secure behavior, backup power, local operation, synchronization, and emergency egress must be defined during design.' },
    ],
    related: [{ label: 'Access control systems', href: '/access-control-system' }, { label: 'Pharmaceutical facility solutions', href: '/industries/pharma' }, { label: 'Fingerprint attendance machines', href: '/fingerprint-attendance-machine' }],
    image: '/campaign/core-systems/door-interlock-desktop-v2.webp', schemaType: 'Service',
  },
  {
    slug: 'visitor-management-system',
    title: 'Visitor Management System for Safer, Faster Check-In',
    primaryKeyword: 'visitor management system',
    keywords: ['visitor management system', 'visitor registration software', 'digital visitor log', 'workplace visitor access', 'visitor management India'],
    description: 'Digitize visitor registration, host coordination, check-in records, visit status, and check-out with Indian Infotech visitor management software.',
    eyebrow: 'Visitor operations',
    intro: [
      'A visitor management system replaces an isolated paper register with a defined digital visit workflow. It helps reception and security teams coordinate registration, host communication, arrival, entry decisions, visit status, and check-out records.',
      'Indian Infotech offers a visitor platform for workplaces that need a clearer front-desk and security process. The implementation is shaped around visitor types, approvals, privacy, entry points, host responsibility, credentials, emergency needs, and existing access systems.',
    ],
    features: [
      { title: 'Visitor registration', body: 'Collect the approved information needed to identify and route a visitor at arrival or preregistration.' },
      { title: 'Host coordination', body: 'Define how hosts are notified and how approval or reception handoff should work.' },
      { title: 'Visit-status records', body: 'Maintain a clearer view of active, completed, and exceptional visits for responsible teams.' },
      { title: 'Entry workflow integration', body: 'Plan badges, approved credentials, access decisions, and check-out around site security rules.' },
    ],
    benefits: ['Reduce dependence on handwritten visitor registers', 'Make host responsibility clearer', 'Improve visibility of active visits', 'Create a consistent check-in and check-out process'],
    integration: 'Visitor registration → host coordination → approved entry process → visit tracking → check-out.',
    industries: ['Corporate offices', 'Pharmaceutical', 'Manufacturing', 'Healthcare', 'Education', 'Hospitality', 'Government'],
    faqs: [
      { question: 'What is a visitor management system?', answer: 'It manages the visitor journey from registration and host coordination through entry, visit status, and check-out.' },
      { question: 'Can visitors be preregistered?', answer: 'Preregistration can be included when the selected workflow, user roles, and deployment capabilities support it.' },
      { question: 'Does visitor management connect to access control?', answer: 'The two can be planned together so approved visitors follow a controlled entry process, subject to system compatibility.' },
      { question: 'Can it replace a paper visitor register?', answer: 'It can digitize the operating record, but the organization must define approved data fields, retention, privacy, fallback, and responsible users.' },
      { question: 'What should be mapped before implementation?', answer: 'Visitor categories, reception points, hosts, approvals, credentials, restricted areas, emergency processes, privacy, and check-out should be documented.' },
    ],
    related: [{ label: 'Explore visitor management software', href: '/software/visitor-management' }, { label: 'Visitor security workflow', href: '/solutions/visitor-security' }, { label: 'Access control systems', href: '/access-control-system' }],
    image: '/campaign/core-systems/easy-visit-desktop-v2.webp', schemaType: 'SoftwareApplication',
  },
  {
    slug: 'entrance-control-system',
    title: 'Entrance Control System for People and Vehicle Movement',
    primaryKeyword: 'entrance control system',
    keywords: ['entrance control system', 'turnstile access control', 'speed gate system', 'flap barrier access', 'workplace entrance management'],
    description: 'Plan flap barriers, turnstiles, boom barriers, screening, and connected access control around workplace entry flow and site conditions.',
    eyebrow: 'Entrance management',
    intro: [
      'An entrance control system manages the physical movement of people or vehicles through a defined point. Flap barriers, tripod or full-height turnstiles, boom barriers, and screening equipment each solve a different flow and security problem.',
      'Indian Infotech scopes entrance hardware around throughput, lane width, authorization method, safety, supervision, environment, civil work, power, network, and operating ownership. The physical equipment is then connected to the appropriate access or visitor workflow.',
    ],
    features: [
      { title: 'Pedestrian entrance options', body: 'Compare flap barriers, tripod turnstiles, and full-height turnstiles around traffic and security needs.' },
      { title: 'Vehicle entry control', body: 'Plan boom barriers and connected authorization for suitable gates and vehicle flows.' },
      { title: 'Identity-system connection', body: 'Coordinate compatible entrance equipment with approved biometric, access, visitor, or operator decisions.' },
      { title: 'Site and safety design', body: 'Confirm lanes, emergency egress, foundations, shelter, power, cabling, supervision, and fallback operation.' },
    ],
    benefits: ['Organize busy pedestrian or vehicle entry points', 'Match physical control to the required security level', 'Connect authorization with actual movement', 'Reduce installation surprises through site-led planning'],
    integration: 'Authorized user or vehicle → access decision → barrier or turnstile movement → event and exception handling.',
    industries: ['Manufacturing', 'Corporate campuses', 'Logistics', 'Construction', 'Education', 'Government', 'Pharmaceutical'],
    faqs: [
      { question: 'What is included in an entrance control system?', answer: 'It can include physical barriers or turnstiles, an access or operator decision, safety devices, power, civil work, network, and operating procedures.' },
      { question: 'What is the difference between a flap barrier and a turnstile?', answer: 'Flap barriers suit managed pedestrian lanes, while tripod and full-height turnstiles provide different levels of physical control and throughput.' },
      { question: 'Can entrance control use biometric authentication?', answer: 'Compatible biometric terminals can provide an authorization input when the entrance controller and safety design support it.' },
      { question: 'Can the same system manage vehicles?', answer: 'Vehicle entry typically uses a purpose-built boom barrier and a suitable authorization or operator workflow.' },
      { question: 'Why must emergency egress be considered?', answer: 'Physical entrance equipment must fit life-safety, evacuation, supervision, and fallback requirements for the actual site.' },
    ],
    related: [{ label: 'Browse entrance-management products', href: '/products#entrance-management' }, { label: 'Entrance management solution', href: '/solutions/entrance-management' }, { label: 'Door access control', href: '/door-access-control-system' }],
    image: '/campaign/core-systems/entrance-control-desktop-v2.webp', schemaType: 'Service',
  },
  {
    slug: 'canteen-management-system',
    title: 'Canteen Management System for Employee Meal Operations',
    primaryKeyword: 'canteen management system',
    keywords: ['canteen management system', 'employee cafeteria management', 'cashless canteen software', 'workplace meal management', 'canteen automation India'],
    description: 'Organize employee identification, meal entitlements, transactions, usage records, and canteen reporting with Indian Infotech software.',
    eyebrow: 'Workplace services',
    intro: [
      'A canteen management system helps a workplace identify employees, apply approved meal entitlements, record transactions, and review service usage. It can replace loosely controlled paper or token processes with a clearer operating record.',
      'Indian Infotech offers biometric canteen management within its workplace software portfolio. Entitlement rules, employee identity, service points, meal periods, exceptions, reporting, devices, and reconciliation ownership are confirmed during solution design.',
    ],
    features: [
      { title: 'Employee identification', body: 'Use a supported identity method to associate a meal transaction with an approved employee record.' },
      { title: 'Entitlement rules', body: 'Define eligible meals, time windows, categories, limits, and approved exceptions.' },
      { title: 'Transaction records', body: 'Create a clearer operational record of validated meal usage at configured service points.' },
      { title: 'Usage reporting', body: 'Support responsible teams with approved operational and reconciliation reports.' },
    ],
    benefits: ['Reduce manual token or register handling', 'Apply meal rules more consistently', 'Improve visibility of workplace canteen usage', 'Support clearer reconciliation responsibilities'],
    integration: 'Employee identity → entitlement validation → meal transaction → operational usage review.',
    industries: ['Manufacturing', 'Pharmaceutical', 'Textile', 'Engineering', 'Corporate campuses', 'Education', 'Healthcare'],
    faqs: [
      { question: 'What is a canteen management system?', answer: 'It manages employee identification, meal eligibility, transaction records, and approved operational reporting for workplace food service.' },
      { question: 'Can canteen access use biometrics?', answer: 'Indian Infotech publishes a biometric canteen workflow. The selected identity device and software compatibility must be confirmed.' },
      { question: 'Can different employees have different entitlements?', answer: 'Rules can be planned around approved employee categories, meal periods, limits, and exceptions where supported by the configuration.' },
      { question: 'Does it manage food inventory?', answer: 'The published scope emphasizes identification, entitlement, transactions, usage records, and reports. Any inventory capability must be confirmed separately.' },
      { question: 'What is needed for implementation?', answer: 'Prepare employee data ownership, meal rules, service points, identity method, exceptions, reports, rollout, and reconciliation responsibilities.' },
    ],
    related: [{ label: 'Explore canteen management software', href: '/software/canteen-management' }, { label: 'Canteen operations solution', href: '/solutions/canteen-operations' }, { label: 'Workforce management software', href: '/workforce-management-software' }],
    image: '/campaign/core-systems/easy-canteen-desktop-v2.webp', schemaType: 'SoftwareApplication',
  },
  {
    slug: 'time-attendance-software',
    title: 'Time Attendance Software for Accurate Workforce Review',
    primaryKeyword: 'time attendance software',
    keywords: ['time attendance software', 'time and attendance system', 'employee time tracking', 'workforce clock-in software', 'attendance payroll integration'],
    description: 'Connect time punches, shifts, leave, exceptions, overtime context, reporting, and approved payroll inputs with Indian Infotech software.',
    eyebrow: 'Time and attendance',
    intro: [
      'Time attendance software provides the review layer between a raw punch and an approved workforce record. It helps responsible teams interpret time events using shifts, leave, weekly patterns, exceptions, overtime context, and local policy.',
      'Indian Infotech connects supported attendance endpoints with Easytime Online and HRMS workflows. The design is confirmed around rules, roles, correction paths, locations, reporting, payroll handoff, and the organization’s current time-office process.',
    ],
    features: [
      { title: 'Time-event collection', body: 'Receive supported attendance events from configured workforce devices and locations.' },
      { title: 'Shift and leave context', body: 'Review recorded time against approved shifts, leave, and operating patterns.' },
      { title: 'Exception workflow', body: 'Define ownership for missed punches, corrections, approvals, and unresolved records.' },
      { title: 'Reports and payroll handoff', body: 'Prepare approved time records for management review or a confirmed downstream workflow.' },
    ],
    benefits: ['Turn raw punches into reviewable time records', 'Reduce manual shift and exception consolidation', 'Make correction ownership clearer', 'Improve the quality of approved payroll inputs'],
    integration: 'Attendance endpoint → time attendance software → shift and exception approval → payroll-ready record.',
    industries: ['Manufacturing', 'Pharmaceutical', 'Textile', 'Corporate offices', 'Retail', 'Logistics', 'Construction'],
    faqs: [
      { question: 'What is time attendance software?', answer: 'It organizes recorded time events with shifts, leave, exceptions, approvals, and reports for workforce review.' },
      { question: 'How is it different from an attendance machine?', answer: 'The machine captures an event; the software applies the operational context needed to review and use that event.' },
      { question: 'Can it handle multiple shifts?', answer: 'Shift handling can be configured where supported, after shift patterns, cross-midnight work, weekly rules, and exceptions are documented.' },
      { question: 'Can it prepare payroll inputs?', answer: 'Approved time records can support payroll preparation once the required fields, rules, and integration method are validated.' },
      { question: 'Can it manage multiple sites?', answer: 'A centralized deployment can support configured locations with appropriate network, device, role, and reporting design.' },
    ],
    related: [{ label: 'Time and attendance HRMS module', href: '/hrms-payroll/time-attendance' }, { label: 'Attendance management software', href: '/attendance-management-software' }, { label: 'Cloud attendance systems', href: '/cloud-attendance-system' }],
    image: '/campaign/core-systems/easytime-desktop-v2.webp', schemaType: 'SoftwareApplication',
  },
];
