import type { Metadata } from 'next';
import { createPageMetadata } from '@/lib/site';
import Link from 'next/link';
import { PageHero } from '../_components/page-hero';
import { SiteFooter } from '../_components/site-footer';
import { SiteHeader } from '../_components/site-header';
import { WorkflowBand } from '../_components/enterprise-route';

export const metadata: Metadata = createPageMetadata({ title: 'Engineering & Implementation', description: 'Practical engineering and implementation support for biometric devices, software, integrations, and rollout requirements.', path: '/engineering' });
const disciplines = ['Product and configuration review', 'Device and entrance-system planning', 'Software workflow mapping', 'Integration and data-flow review', 'Testing, training, and rollout', 'Post-deployment support ownership'];
export default function EngineeringPage() { return <main><SiteHeader /><PageHero eyebrow="Engineering" title="The useful work happens between the device, the policy, and the people using it." description="Use this page to frame an implementation conversation across hardware, software, site conditions, and operating ownership. Detailed engineering claims are confirmed project by project." marker="II / ENGINEERING" /><section className="section route-detail-intro"><div><p className="section-kicker">Implementation lens</p><h2>Design the handoffs before the handover.</h2></div><div><p>Indian Infotech’s portfolio spans physical devices and workforce software. A clear delivery plan makes the connection understandable to administrators, facilities, security, and HR teams.</p><Link className="button button-primary" href="/contact?topic=engineering">Start an engineering brief <span aria-hidden="true">↗</span></Link></div></section><section className="route-dark-section"><div className="section-heading split-heading"><div><p className="section-kicker light">Delivery sequence</p><h2>From discovery to support.</h2></div><p>Use this sequence as a planning frame. Scope, ownership, and technical prerequisites are confirmed before commitment.</p></div><WorkflowBand steps={disciplines} /></section><section className="section"><div className="section-heading"><p className="section-kicker">Engineering conversations</p><h2>Bring the right questions to the room.</h2></div><div className="route-related-grid"><div><h3>System questions</h3><ul><li>What people, locations, and entry points are in scope?</li><li>Which attendance, access, visitor, or canteen workflow matters first?</li><li>Which existing systems need a verified connection?</li></ul></div><div><h3>Delivery questions</h3><ul><li>Who owns policy, configuration, support, and training?</li><li>What media, documents, and approvals are required?</li><li>What must be tested before rollout?</li></ul></div></div></section><SiteFooter /></main>; }
