export type Insight = {
  slug: string;
  category: 'Blog' | 'Company update';
  date: string;
  title: string;
  summary: string;
  image: string;
  sourceUrl?: string;
  researchNote?: string;
  keyTakeaways?: readonly string[];
  sources?: readonly { title: string; publisher: string; year: string; url: string }[];
  cta?: { eyebrow: string; text: string; href: string; label: string };
  sections: readonly { title: string; body: string; points?: readonly string[]; ordered?: boolean }[];
};

export const insights: readonly Insight[] = [
  {
    slug: 'contract-workforce-management-auditable-model',
    category: 'Blog',
    date: '24 September 2026',
    title: 'Contract Workforce Management: An Auditable Model for Attendance, Access & Payroll',
    summary: 'A research-led operating model for connecting contractor rosters, shift attendance, site access, exception review and approved payroll inputs without losing accountability at handoffs.',
    image: '/campaign/product-moments/contract-workforce-v1.png',
    researchNote: 'This is a systems-design synthesis, not a labour-law opinion or a claim that software alone ensures compliance. It draws on the ILO’s non-binding worker-data guidance, NIST log-management guidance, India’s DPDP Act as provisions come into force, and Indian Infotech’s published EasyTime and HRMS scope.',
    keyTakeaways: ['Keep worker assignment, attendance events, access permission and payroll approval as linked but distinct records.', 'Preserve original events; record corrections with a reason, reviewer and timestamp.', 'Give contractors time-bounded access only after a responsible site owner approves the assignment.', 'Treat workforce records as personal data: define purpose, access, retention and a way to raise corrections.'],
    sources: [
      { title: 'Protection of workers’ personal data: ILO code of practice', publisher: 'International Labour Organization', year: '1997', url: 'https://www.ilo.org/public/libdoc/ilo/1997/97B09_118_engl.pdf' },
      { title: 'Guide to Computer Security Log Management (SP 800-92)', publisher: 'National Institute of Standards and Technology', year: '2006', url: 'https://csrc.nist.gov/pubs/sp/800/92/final' },
      { title: 'Digital Personal Data Protection Act, 2023', publisher: 'Ministry of Electronics and Information Technology, Government of India', year: '2023', url: 'https://www.meity.gov.in/static/uploads/2024/02/Digital-Personal-Data-Protection-Act-2023.pdf' },
      { title: 'EasyTime Online attendance software', publisher: 'Indian Infotech', year: 'Current product page', url: '/software/easytime-online' },
      { title: 'HRMS & Payroll', publisher: 'Indian Infotech', year: 'Current product page', url: '/software/hrms-payroll' },
    ],
    cta: { eyebrow: 'Related systems', text: 'Review the published EasyTime attendance workflow and HRMS & Payroll modules. Exact integrations and configuration are confirmed for each deployment.', href: '/software/easytime-online', label: 'Explore EasyTime Online' },
    sections: [
      { title: 'Abstract', body: 'Contractor operations often cross several boundaries: a vendor supplies a roster, a site owner assigns people to shifts, an attendance system records events, an access system authorizes entry, and payroll staff review payable time. The risk is not simply a missing feature. It is an unowned handoff: two records disagree, a correction overwrites the original, or a worker remains authorized after an assignment ends. A dependable model makes each handoff explicit and reviewable.' },
      { title: '1. Scope the problem before choosing the system', body: 'Start with the operating question: who needs to be accounted for, at which site, during which approved assignment and shift, and who is responsible for reviewing an exception? Build a process map from contractor onboarding through assignment end. Include the agency, site security, line manager, HR, payroll and system administrator. The ILO’s worker-data code is useful here because it treats collection, purpose, access, storage and communication as governance questions—not merely database fields. It is guidance, not a substitute for local law.' },
      { title: '2. Model the records as a chain, not one master sheet', body: 'A useful reference model links six record types while keeping their purposes separate:', ordered: true, points: ['Organization and supplier: who is accountable for the supplied workforce and contract scope.', 'Worker identity: a stable internal identifier and only the identity attributes needed for the approved process.', 'Assignment: site, work area, responsible sponsor, start and end dates, and the role that determines access.', 'Work schedule: shift, location, approved changes and the person who owns the schedule.', 'Events and exceptions: original attendance punches, gate or reader events, corrections, reason, reviewer and time of decision.', 'Payroll input: the approved attendance totals or exceptions sent to payroll, with a clear handoff and reconciliation status.'] },
      { title: '3. Connect attendance to access without confusing the signals', body: 'An attendance event answers “what time event was recorded?” An access decision answers “was this credential permitted at this door, in this zone, at that moment?” Neither one alone proves that a person performed a particular job or that a contractor met every contractual or safety requirement. Connect the records with an assignment identifier and timestamp, then let the relevant owner decide what the event means. A denied access event should not silently become an attendance absence; a valid punch should not automatically grant permission to a restricted area.' },
      { title: '4. Preserve the event trail through exceptions', body: 'Late punches, missed swipes, device outages, roster changes and shift swaps are normal operational events. A robust workflow keeps the source event and adds a correction record instead of replacing history. The correction should identify the old and new values, a reason, the approver and the time it was made. NIST’s log-management guidance emphasizes a lifecycle for generating, transmitting, storing, accessing, analyzing and disposing of logs; applying that discipline to attendance and access records makes later review much more useful.', points: ['Require a named reviewer for material changes.', 'Separate the person who requests a correction from the person who approves it where the operation allows.', 'Flag duplicate, overlapping, missing and out-of-window events for review.', 'Synchronize device, server and payroll clocks and document any known time offset.', 'Restrict export and keep an audit trail for who viewed or changed records.'] },
      { title: '5. Make payroll a controlled handoff', body: 'Attendance software can prepare reviewed inputs; payroll policy still belongs to the employer and its authorized payroll team. Before a period closes, compare the assigned roster with captured events, resolve exceptions, confirm approved overtime and leave treatment, then reconcile the exported totals against the receiving payroll system. Keep a clear status for each stage—prepared, reviewed, exported, accepted and corrected—so that “sent” is not confused with “successfully posted.” EasyTime Online’s published scope includes attendance, shifts, leave, overtime review and reports; HRMS & Payroll describes the downstream people and payroll workflow. Exact interfaces and rules need to be confirmed for a particular deployment.' },
      { title: '6. Keep privacy and contractor dignity in the design', body: 'Worker data is operationally valuable and personally sensitive. Define the purpose for every field, avoid collecting data “just in case,” limit access by role and site, set retention according to actual business and legal needs, and make a correction path visible to workers and contractor representatives. The Indian DPDP Act establishes a framework for digital personal data, with provisions brought into force by government notification in phases. A deployment must assess the rules and obligations applicable at its launch date; this article is not legal advice. Where biometric authentication is used, protect templates and identifiers, provide an appropriate fallback, and never use an attendance record as a proxy for unrelated performance decisions.' },
      { title: '7. Measure the operating process, not just device uptime', body: 'A pilot should measure whether the end-to-end record becomes easier to trust. Establish a baseline before rollout and review trends with the people who handle exceptions.', points: ['Roster-to-assignment completeness: active workers with an approved assignment divided by all active roster entries.', 'Exception ageing: time from exception creation to a recorded decision, reported by site and type.', 'Correction traceability: corrected records with an approver, reason and original event preserved.', 'Payroll reconciliation: exported totals that the receiving process accepts on first review.', 'Access hygiene: expired assignments whose access rights were removed within the site’s target window.', 'Worker resolution: time to respond to an attendance or identity correction request.'] },
      { title: '8. A practical pilot sequence', body: 'Choose one site, one contractor group and a representative shift. Map the current process; assign owners; agree on the minimum data set; configure approved attendance and access points; test normal events and failure cases; run the new and old reconciliation in parallel for a defined period; then review exceptions with payroll, security and contractor representatives before expanding. Include power or network interruption, a shift change, a late arrival, an approved correction, a lost credential and assignment expiry in the acceptance checklist.' },
      { title: 'Limitations and conclusion', body: 'A system can improve visibility and preserve evidence, but it cannot determine whether every underlying roster, wage rule, contract, identity check or safety approval is legally correct. Those responsibilities remain with the relevant employer, principal employer, contractor and qualified advisers. The strongest deployment is therefore not the one with the most sensors; it is the one with clear ownership, minimal data, reviewable exceptions and a payroll handoff that can be explained months later.' },
    ],
  },
  {
    slug: 'biometric-access-control-door-interlock-design',
    category: 'Blog',
    date: '24 September 2026',
    title: 'Biometric Access Control & Door Interlocks: A Risk-Based Design Guide',
    summary: 'A technical guide to connecting identity readers, access policy, door interlocking, emergency release and event review in controlled workplace environments.',
    image: '/campaign/product-moments/door-interlock-v1.png',
    researchNote: 'The design discussion synthesizes NIST’s facility-access and log-management guidance with worker-data and Indian privacy references. NIST SP 800-116 concerns US federal PIV credentials; it is used here as a risk-based design reference, not as an Indian compliance standard or a claim that a listed product is PIV-certified.',
    keyTakeaways: ['Separate identity verification, access authorization and door-control state.', 'Write down safe behavior for power, network, sensor, fire-alarm and emergency-release conditions before installation.', 'Test interlock logic and egress with the actual doors and life-safety design.', 'Use the least intrusive credential that meets assessed risk, and define an accessible fallback.'],
    sources: [
      { title: 'Guidelines for the Use of PIV Credentials in Facility Access (SP 800-116 Rev. 1)', publisher: 'National Institute of Standards and Technology', year: '2018', url: 'https://csrc.nist.gov/pubs/sp/800/116/r1/final' },
      { title: 'Guide to Computer Security Log Management (SP 800-92)', publisher: 'National Institute of Standards and Technology', year: '2006', url: 'https://csrc.nist.gov/pubs/sp/800/92/final' },
      { title: 'Protection of workers’ personal data: ILO code of practice', publisher: 'International Labour Organization', year: '1997', url: 'https://www.ilo.org/public/libdoc/ilo/1997/97B09_118_engl.pdf' },
      { title: 'Digital Personal Data Protection Act, 2023', publisher: 'Ministry of Electronics and Information Technology, Government of India', year: '2023', url: 'https://www.meity.gov.in/static/uploads/2024/02/Digital-Personal-Data-Protection-Act-2023.pdf' },
      { title: 'Door Interlock System', publisher: 'Indian Infotech', year: 'Current product page', url: '/products/door-interlock-system' },
      { title: 'AI-70 biometric attendance and access terminal', publisher: 'Indian Infotech', year: 'Current product page', url: '/products/ai-70' },
    ],
    cta: { eyebrow: 'Related systems', text: 'Indian Infotech publishes a Door Interlock System and biometric access products. Final reader, controller, door hardware, interfaces and safety behavior must be assessed and confirmed for the site.', href: '/products/door-interlock-system', label: 'Explore Door Interlock System' },
    sections: [
      { title: 'Abstract', body: 'A controlled entrance is a chain of decisions: identify a person, evaluate permission, command a controller, observe the door and record the result. A door interlock adds a state constraint so two connected doors cannot be opened in an unsafe sequence. This guide describes a risk-based engineering model for factories, offices and controlled rooms, where security, safe egress, uptime and worker privacy must be considered together.' },
      { title: '1. Define the protected outcome', body: 'Begin with the asset, hazard or process the door is meant to protect. A main lobby, a server room, a pharmaceutical airlock and a pedestrian turnstile have different consequences when access is delayed or granted incorrectly. Map zones, doors, user groups, operating hours, visitor routes, emergency exits and responsible owners. NIST SP 800-116 Rev. 1 describes a risk-based approach to credential selection for US federal facility access; its useful transferable lesson is to choose the authentication strength in relation to assessed risk, while its PIV-specific controls are not a substitute for local requirements.' },
      { title: '2. Separate the system into four decision layers', body: 'A clear architecture avoids treating a biometric terminal as if it alone performs every security function:', ordered: true, points: ['Identity capture and verification: the reader compares the presented credential or biometric against an enrolled identity using its supported method.', 'Authorization: a controller or approved policy service checks identity, role, door, time window and assignment status.', 'Door control: relays and sensors act on the lock, barrier or interlock controller and report the physical state.', 'Event management: systems record the request, decision, door state, alarms, operator action and any later correction.'] },
      { title: '3. Specify the interlock as a state machine', body: 'Write the intended sequence before wiring it. A simplified two-door model might allow Door A to unlock only when Door B is confirmed closed and not in an alarm state; after A closes and its sensor confirms the transition, B can be considered. The actual state model must reflect the room’s purpose, air-pressure requirements, emergency egress and the selected controller. Define “closed,” “locked,” “occupied,” “fault” and “emergency release” in testable terms. A software screen that says “granted” is not proof that the door physically latched.' },
      { title: '4. Decide fault and emergency behavior with safety owners', body: 'There is no universal “fail-safe” or “fail-secure” setting suitable for every door. On loss of power, network, controller health or sensor feedback, the required state depends on life-safety rules, the lock and door hardware, facility procedures, and the hazard being controlled. Document a cause-and-effect matrix with the fire and life-safety owner, facilities engineer and security owner. Confirm free egress, manual override, alarm signaling and post-event reset behavior using qualified site personnel before commissioning. Never let a product brochure substitute for the approved site safety design.' },
      { title: '5. Treat biometric data as one credential option', body: 'Biometrics can make a credential convenient, but it introduces enrollment, template protection, false accept/reject, environmental and worker-trust questions. Assess whether a face or fingerprint is necessary for each zone or whether a card, PIN, staffed checkpoint or combined factor is enough. Define an accessible alternate route for a failed read, injury, protective equipment, disability, lighting issue or device outage. Limit who can enroll, replace or remove a credential; protect stored templates; document how long enrollment data remains; and provide a way to challenge an incorrect denial. The ILO worker-data guidance is a useful reminder to make purpose, access, security and communication part of the design.' },
      { title: '6. Build an event record useful for investigation', body: 'A minimally useful event includes a stable identity reference, door or zone, time, requested method, authorization result, controller state and event identifier. Record alarms and manual overrides with the operator and reason. Keep timestamps synchronized across readers, controllers and monitoring systems. Protect event logs from casual alteration and restrict exports: they can reveal worker schedules and movement patterns. NIST SP 800-92 describes planning for log generation, transmission, storage, access, analysis and disposal; use those lifecycle questions when sizing retention and assigning log ownership.' },
      { title: '7. Commission using scenarios, not a single successful swipe', body: 'Run each test with the installed reader, controller, lock, sensors, doors, network and emergency interface. Record expected behavior, observed behavior, evidence and the person who accepted the result.', points: ['Authorized user at an assigned door and time; unauthorized user; expired assignment; revoked credential.', 'Both doors closed, one door held open, a sensor disagreement, door forced open and repeated credential presentation.', 'Network loss, controller reboot, reader failure, power interruption and restored operation.', 'Fire alarm, emergency release, manual override, free-egress check and safe re-entry/reset.', 'Face/fingerprint mismatch, dirty sensor, PPE or low-light condition, and the agreed human fallback.', 'Correct event time, duplicate event handling, alarm routing, audit export and access to retained records.'] },
      { title: '8. Match the technology to the published product scope', body: 'Indian Infotech’s public catalogue includes a Door Interlock System for controlled movement between secured areas and biometric attendance/access terminals such as AI-70. Those pages describe the product family, not a guaranteed compatibility matrix. Confirm the exact reader, controller, lock, door closer, sensor, emergency interface, network, software version and support scope in the project design. A site assessment should decide whether the system should release, stay secured or require local intervention during each failure condition.' },
      { title: 'Limitations and conclusion', body: 'This article is an engineering-planning aid, not a life-safety approval, penetration test or legal opinion. NIST’s PIV publication is written for a specific US federal credential environment; product selection and commissioning in India must follow site-specific safety, privacy, security and contractual requirements. The reliable design is the one whose policy, physical state, exception route and emergency behavior have each been agreed, documented and tested.' },
    ],
  },
  {
    slug: 'indian-infotech-publishes-product-planning-guides',
    category: 'Company update',
    date: '24 September 2026',
    title: 'Indian Infotech Publishes In-Depth Guides for Workforce and Access Planning',
    summary: 'A new product-focused editorial series helps operations teams plan contractor attendance, payroll handoffs, biometric access, and door-interlock behavior with clearer technical context.',
    image: '/campaign/core-systems/workplace-software-poster.png',
    researchNote: 'Company website update. This announcement is about new educational content, not a new product launch, certification, customer deployment or feature release.',
    keyTakeaways: ['The first guide connects contractor rosters, attendance exceptions, access permissions and payroll review.', 'The second explains risk-based access-control and door-interlock planning, including commissioning and emergency behavior.', 'Product compatibility and project scope remain subject to site assessment and written confirmation.'],
    sources: [
      { title: 'Contract Workforce Management: An Auditable Model for Attendance, Access & Payroll', publisher: 'Indian Infotech Insights', year: '2026', url: '/insights/contract-workforce-management-auditable-model' },
      { title: 'Biometric Access Control & Door Interlocks: A Risk-Based Design Guide', publisher: 'Indian Infotech Insights', year: '2026', url: '/insights/biometric-access-control-door-interlock-design' },
      { title: 'EasyTime Online', publisher: 'Indian Infotech', year: 'Current product page', url: '/software/easytime-online' },
      { title: 'Door Interlock System', publisher: 'Indian Infotech', year: 'Current product page', url: '/products/door-interlock-system' },
    ],
    cta: { eyebrow: 'Explore the portfolio', text: 'Start with published product information, then confirm the exact configuration, compatibility and deployment scope with the Indian Infotech team.', href: '/products', label: 'Explore products' },
    sections: [
      { title: 'An editorial update for teams planning connected workplaces', body: 'Indian Infotech has published two detailed product-planning guides for organizations reviewing workforce attendance, contractor access and controlled entry. The articles bring operational workflows and design limits into the same conversation, so buyers can ask more useful questions before a system is scoped.' },
      { title: 'Guide one: contractor workforce records that survive handoffs', body: 'The contractor-management article follows a record from roster and site assignment through shift attendance, exception review, access authorization and payroll preparation. It lays out a practical control model: retain source events, document corrections, assign review owners, track access expiry and measure how quickly exceptions are resolved. The guide references International Labour Organization worker-data guidance, NIST log-management material and the Indian privacy framework, while clearly distinguishing planning advice from legal compliance.' },
      { title: 'Guide two: designing biometric access and door interlocks', body: 'The access-control article treats reader identity, authorization policy, physical door state and event records as separate parts of one system. It explains why emergency release, egress, sensor behavior, power loss and network failure must be written into the approved site design and tested with the installed hardware. NIST’s facility-access publication is used as a risk-based reference, not as a claim of Indian certification or PIV compatibility.' },
      { title: 'How the guides connect to the product portfolio', body: 'Indian Infotech’s published portfolio includes EasyTime Online for attendance and workforce workflows, HRMS & Payroll modules, biometric attendance and access terminals, entrance-management devices and door-interlock products. These resources help teams frame a requirement; they do not imply that every device, software version or integration works together in every configuration. The site’s product pages and a scoped technical discussion remain the right sources for project-specific selection.' },
      { title: 'What buyers can take into their next review', body: 'Before a product demonstration or tender, prepare the workforce and contractor categories, sites and shifts, doors and zones, exception owners, payroll handoff, emergency behavior, privacy needs, network conditions and support expectations. A clear first brief makes the next technical discussion more specific and helps both teams identify what still needs verification.' },
    ],
  },
  {
    slug: 'easytime-cloud-attendance-benefits',
    category: 'Blog',
    date: '23 August 2024',
    title: 'Why Your Company Needs EasyTime: The Benefits of Rent-Based Cloud Attendance Management',
    summary: 'From the original Indian Infotech blog: a detailed look at how a rent-based cloud attendance model can change rollout costs, reporting, support, and day-to-day workforce administration.',
    image: '/insights/cloud-attendance.png',
    sourceUrl: 'https://indianinfotech.org/why-your-company-needs-easytime-the-benefits-of-rent-based-cloud-attendance-management/',
    sections: [
      { title: 'The problem with traditional attendance systems', body: 'Traditional attendance systems can require a large upfront investment in devices, servers, installation, maintenance, and upgrades. Manual records and disconnected spreadsheets also create missed punches, inaccurate timesheets, slow approvals, and avoidable payroll disputes.' },
      { title: 'Why teams consider a cloud model', body: 'EasyTime is a rent-based cloud attendance system designed to reduce the infrastructure burden while keeping attendance information available to the people who review it. The practical question is not whether cloud is fashionable; it is whether the operating model makes attendance easier to run across the organization.' },
      { title: '1. Cost and rollout flexibility', body: 'A subscription model can make the first rollout easier to plan than a large capital purchase. Teams can confirm the right device mix, locations, users, and software scope before expanding the system, instead of committing every site to the same configuration on day one.' },
      { title: '2. Easier setup and maintenance', body: 'A cloud platform can reduce the need for local servers and repeated software maintenance. The remaining work still matters: define attendance policies, connect approved devices, assign administrators, test exceptions, and document who owns support at each location.' },
      { title: '3. Anywhere access and real-time reporting', body: 'HR and operations teams can review attendance from a central view across offices, plants, and remote teams. Reports can help surface absenteeism, overtime, shift exceptions, and missing records before they become payroll or compliance problems.', points: ['Review attendance from approved locations', 'Identify missing or unusual punches', 'Track shift and overtime exceptions', 'Prepare validated records for payroll'] },
      { title: '4. Better employee and manager experience', body: 'A clear attendance workflow gives employees a way to see records, submit leave requests, and understand schedules while managers can review exceptions with context. Transparency reduces repetitive questions and makes responsibility easier to assign.' },
      { title: '5. What to confirm before rollout', body: 'The final design should be based on the organization’s real operating model.', points: ['Workforce size, shifts, and locations', 'Device and authentication requirements', 'Leave, overtime, and approval policies', 'Network, offline, and data-handling expectations', 'Payroll or ERP integration scope', 'Training, escalation, and support ownership'] },
      { title: 'Where EasyTime fits', body: 'Manufacturing teams can coordinate multiple shifts, retail groups can review attendance across stores, and distributed or remote teams can use a shared operating view. The right configuration depends on the site assessment and should be confirmed before procurement.' },
    ],
  },
  {
    slug: 'ai-in-production-lines',
    category: 'Blog',
    date: '23 August 2024',
    title: 'How AI Technology Is Changing the Game in Production Lines',
    summary: 'From the original Indian Infotech blog: an overview of AI use in production, including process monitoring, quality inspection, supply planning, and the human decisions that still guide deployment.',
    image: '/insights/ai-production-line.png',
    sourceUrl: 'https://indianinfotech.org/how-ai-technology-is-changing-the-game-in-production-lines/',
    sections: [
      { title: '1. What is AI and why does it matter?', body: 'Artificial intelligence enables software and machines to interpret information, identify patterns, and support decisions that would otherwise require constant manual review. On a production line, its value comes from making operational signals easier to act on—not from adding an impressive label to a device.' },
      { title: '2. How AI boosts production efficiency', body: 'AI can monitor equipment and process data to identify patterns before a small issue becomes a stoppage. Predictive maintenance, process optimization, and real-time alerts can help teams reduce downtime and keep production moving at a more consistent pace.' },
      { title: '3. Keeping quality in check', body: 'AI-powered cameras and sensors can inspect products for defects or inconsistencies while work is still in progress. Detecting scratches, assembly errors, or dimensional variation earlier can reduce waste and give quality teams a clearer record of where problems begin.' },
      { title: '4. AI in supply-chain planning', body: 'Production performance depends on materials, inventory, dispatch, and logistics as much as the line itself. AI-assisted forecasting can help estimate demand, plan raw-material requirements, identify bottlenecks, and coordinate finished-goods movement with more evidence.' },
      { title: '5. Connected workforce and access workflows', body: 'The production line is also a people and safety environment. Workforce software can support employee scheduling and performance records, while biometric access control can help ensure that only authorized people enter controlled areas. These workflows should match site roles, safety procedures, and privacy responsibilities.' },
      { title: '6. Where Indian Infotech can help', body: 'Indian Infotech brings together workforce systems, access control, and workplace technology for operating environments that need clearer records. HRMS and attendance workflows can support the workforce; biometric access can support controlled entry; and media systems can distribute approved SOPs, training, or safety content across displays.' },
      { title: '7. Real-world production examples', body: 'Automotive plants use AI-assisted inspection and robotics for repeatable precision. Electronics manufacturers inspect small components for defects. Food and beverage teams use data to improve quality, throughput, and demand planning. The technology varies, but the operating principle is consistent: connect the signal to a decision and assign a person to review the outcome.' },
      { title: '8. What comes next', body: 'Future production environments will connect machines, people, quality systems, and supply-chain signals more closely. A responsible path starts with one measurable bottleneck, reliable data, a defined fallback when the system is uncertain, and a rollout plan that employees can understand.' },
    ],
  },
] as const;
