import type { Metadata } from 'next';
import { createPageMetadata } from '@/lib/site';
import Link from 'next/link';
import { PageHero } from '../_components/page-hero';
import { SiteFooter } from '../_components/site-footer';
import { SiteHeader } from '../_components/site-header';

export const metadata: Metadata = createPageMetadata({ title: 'Technology & Channel Partners', description: 'Partner enquiry route for Indian Infotech channel, technology, and implementation ecosystem conversations.', path: '/partners' });
export default function PartnersPage() { return <main><SiteHeader /><PageHero eyebrow="Partners" title="Build the right ecosystem around the customer’s operating context." description="Partner names, certifications, and ecosystem claims will be published after their scope, validity, and display permission are confirmed." marker="II / PARTNERS" /><section className="section route-detail-intro"><div><p className="section-kicker">Partner conversations</p><h2>Channel, technology, and implementation collaboration.</h2></div><div><p>Use the enquiry route to share your organization, geography, capability, and the customer problem you want to solve. A public partner directory will follow once approved records are available.</p><Link className="button button-primary" href="/contact?topic=partner">Start a partner enquiry <span aria-hidden="true">↗</span></Link></div></section><section className="route-dark-section"><div className="section-heading split-heading"><div><p className="section-kicker light">Evidence standard</p><h2>Make the relationship useful to the buyer.</h2></div><p>Every published partner record should state what is supported, who owns the relationship, and where the customer can get help.</p></div><div className="route-link-list"><span>Verified scope</span><span>Current validity</span><span>Display permission</span><span>Support ownership</span></div></section><SiteFooter /></main>; }
