import type { Metadata } from 'next';
import { createPageMetadata } from '@/lib/site';
import Image from 'next/image';
import Link from 'next/link';
import { PageHero } from '../_components/page-hero';
import { SiteFooter } from '../_components/site-footer';
import { SiteHeader } from '../_components/site-header';
import { companyFacts } from '../content';

export const metadata: Metadata = createPageMetadata({ title: 'Company Overview', description: 'Learn about Indian Infotech, founded in Ahmedabad in 2011, and its connected hardware, software, and workplace systems.', path: '/company' });
export default function CompanyPage() { return <main><SiteHeader /><PageHero eyebrow="Company" title="A connected systems company, rooted in Ahmedabad." description="Indian Infotech brings together biometric hardware, access and entrance systems, workforce software, HRMS, payroll, and workplace operations for organizations that need practical deployment support." marker="II / COMPANY" /><section className="section"><div className="company-legacy-image"><Image src="/company/about-banner.webp" alt="Workplace team using technology in an office environment" width={1568} height={830} priority /></div><div className="fact-strip route-facts">{companyFacts.map((fact) => <div key={fact.label}><strong>{fact.value}</strong><span>{fact.label}</span></div>)}</div><div className="route-detail-intro"><div><p className="section-kicker">Company story</p><h2>Established in 2011. Focused on the work between identity, entry, and operations.</h2></div><div><p>Indian Infotech was incorporated in 2011 as a partnership firm with an experienced team in HRMS, office automation, and pharma clean-room door interlock systems. It now brings together biometric hardware, access and entrance systems, workforce software, and workplace operations from Ahmedabad, Gujarat, India.</p><p>The published company scope includes total time-office management, secured access through door-interlock systems, HRMS, office automation, and pharma clean-room products.</p><p>Detailed customer outcomes, certifications, leadership, and partner claims remain evidence-gated until approved source material is supplied.</p><Link className="button button-primary" href="/contact">Connect with the company <span aria-hidden="true">↗</span></Link></div></div></section><section className="route-dark-section"><div className="section-heading split-heading"><div><p className="section-kicker light">What to explore</p><h2>See the systems in context.</h2></div><p>Move from company context into products, software, solutions, and the support path that fits your question.</p></div><div className="route-link-list"><Link href="/products">Products <span>↗</span></Link><Link href="/software">Software <span>↗</span></Link><Link href="/solutions">Solutions <span>↗</span></Link><Link href="/engineering">Engineering <span>↗</span></Link><Link href="/support">Support <span>↗</span></Link></div></section><SiteFooter /></main>; }
